import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function BaseLayout ({ children }: { children: React.ReactNode }) { 

return (
  <html>
   <body> 
    <div className="min-h-screen flex flex-col">
      
      <div className="flex-1 container mx-auto px-4">{children}</div>
      <footer className="p-6 text-center border-t text-gray-400">
        © 2026 CMS
      </footer>
    </div>
    </body>
    </html>
);
}
